DefaultContentLanguage = "hu"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://hungaricus.github.io/adlibrum-ananke"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "hu-hu"
theme = "ananke"
title = "Ad Librum kiadók"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = "https://facebook.com/adlibrum"
favicon = ""
featured_image = "/uploads/Olvasni_menő.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 2
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
