DefaultContentLanguage = "hu"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://hungaricus.github.io/adlibrum-ananke"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "hu-hu"
theme = "ananke"
title = "Ad Librum kiadók"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 2
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
